### ISSUE TITLE
Feature request: rotations and color flips

### ISSUE THREAD

**Issue by bixbyr** [sanderland/pysgf#1]
This is a really nice library, it is pythonic and does things the right way.

I'm using it for a tsumego web application which involves applying random rotations and color flips to a problem to emphasize the shape over pure memorization. The request is to add a method for rotating an SGFNode (and all of it's children) by 90, 180, or 270 degrees, a similar method for a flip in the x direction for a node and all of its children, and a recursive transformation for swapping colors.

I was starting to implement this and doing it the right way involved interacting with the internals of the package so it seemed to make more sense to add that functionality to the library itself.

**Comment by sanderland** [comment]
You can PR it to the package and i'll accept it.
