### ISSUE TITLE
Is it possible to read the comments in SGF files with Python?

### ISSUE THREAD

**Issue by phdsmhong** [sanderland/pysgf#2]
Hello, I was wondering whether I could get advice. I am trying to read the comments written in SGF files with Python. Is there any python module that reads them? Any advice would be greatly appreciated. 

BTW, thank you for sharing Katrain. My skills in go greatly improved with it. :)

**Comment by sanderland** [comment]
which comments? C[] ?

**Comment by phdsmhong** [comment]
Thank you for your reply! :)

By "comments", I mean the short descriptions attached to each move. Please see the attached file. I wonder whether there is a quick command in python that reads these comments and associate them with stone positions. I will use these comments for training my deep learning models.

<img width="811" alt="sgf_comments" src="https://user-images.githubusercontent.com/109200843/190426030-678c9f8c-e5e4-423e-8552-c138713ee88f.png">

**Comment by sanderland** [comment]
I would think just  `node.get_list_property("C")` or `node.get_property('C')` would get you what you want.
